add codeowners file; update token permission to read only for workflow and validate GO_VERSION is of the correct format and length

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -2,6 +2,7 @@ name: Linux
 
 on: [pull_request]
 
+permissions: read-all
 jobs:
   unit-tests:
     name: Linux unit tests
@@ -11,12 +12,22 @@ jobs:
         with:
           path: src/github.com/aws/amazon-ecs-agent
       - name: get GO_VERSION
+        id: get-go-version
         run:  |
           cd $GITHUB_WORKSPACE/src/github.com/aws/amazon-ecs-agent
-          echo "GO_VERSION=$(cat GO_VERSION)" >> $GITHUB_ENV
+          set -eou pipefail
+          go_version=$(cat -e GO_VERSION)
+          go_version=${go_version%?}
+          go_version_length=${#go_version}
+          go_version_re="^([0-9]+\.){1,2}([0-9]+)$"
+          if ! [[ $go_version_length -le 10 && $go_version =~ $go_version_re ]] ; then
+            echo "invalid GO version"
+            exit 1
+          fi
+          echo "::set-output name=GO_VERSION::$go_version"
       - uses: actions/setup-go@v2
         with:
-          go-version: ${{ env.GO_VERSION }}
+          go-version: ${{ steps.get-go-version.outputs.GO_VERSION }}
       - uses: actions/checkout@v2
         with:
           submodules: true
